### ISSUE TITLE
Using PTAXSIM to simulate residential exemption policies

### ISSUE THREAD

**Issue by rross0** [ccao-data/ptaxsim#18]
I want to test the impact of different hypothetical values of a Homeowners' Exemption in Cook County on 1) progressivity of the tax structure and 2) the cost of modeling errors to low-income residents. I want to answer the question "What would happen in Cook County if Illinois increased the EAV amount of the Homeowners' Exemption by 100%? 200%? 300%? etc."

A naïve approach would be to use parcels' estimated market values from Cook County's open data and apply a fixed tax rate while varying the value of the Homeowners Exemption. This approach would not account for the impact of the Homeowners exemption on the overall tax base, and therefore on the tax rate applied in each iteration. 

Reading the PTAXSIM documentation, it does not appear clear to me that it is easy to use PTAXSIM to simulate the impact of policy changes on the entire tax base. 

I have to complete this by Thursday of next week. Is there a way to easily user PTAXSIM to simulate this scenario?

**Comment by ccao-jardine** [comment]
Howdy. Does the "Many PINS: Altering exemptions" counterfactual section of [this vignette](https://ccao-data.github.io/ptaxsim/articles/exemptions.html#changing-exemptions-1) help?

**Comment by rross0** [comment]
grumble.... make me read.... grumble.

**Comment by rross0** [comment]
[Here in the document](https://ccao-data.github.io/ptaxsim/articles/exemptions.html#changing-exemptions-1): 
`t_agency_dt_new_exe[
  t_tc_sum_new_exe,
  on = .(year, tax_code),
  **agency_total_eav := agency_total_eav + exe_total**
]`

Here, exe_total will be a positive number? And agency_total_eav does not include the value of exemtions?

**Comment by dfsnow** [comment]
@rross0 That's right. `exe_total` should be the amount the base _grows_ in each tax code from removing the freeze, so it should mostly be positive. In cases where there are more senior exemptions than freeze exemptions, it could also be negative.

`agency_total_eav` in this case already includes the value of all exemptions, so `exe_total` is just the _change_ in exemption EAV for each tax code.

**Comment by rross0** [comment]
@dfsnow does this work? I'm just doing a loop incrementally increasing the value of HE exemption. Below is part of that loop:

`for(m in 0:20){
# Set exemption value
  t_pin_dt_new_exe <- lookup_pin(t_years, t_pins)
  t_pin_dt_new_exe[, tax_code := lookup_tax_code(year, pin)]
  
  t_tc_sum_new_exe <- t_pin_dt_new_exe[
    , .(exe_total = sum(exe_homeowner*m)),
    by = .(year, tax_code)
  ]
  
  # Calculate bases by adding agency total and the exemption amount
  t_agency_dt_new_exe <- lookup_agency(t_years, t_pin_dt_new_exe$tax_code)
  t_agency_dt_new_exe[
    t_tc_sum_new_exe,
    on = .(year, tax_code),
    agency_total_eav := agency_total_eav + exe_total
  ]`

**Comment by rross0** [comment]
This is what I got. It's consistent with what I expected, but I want to make sure I got the base calc right:
![image](https://github.com/ccao-data/ptaxsim/assets/12952187/351872b9-03da-4529-ab53-c6ec517a72d8)

**Comment by dfsnow** [comment]
I think in your case you need to flip the sign here:

```r
    agency_total_eav := agency_total_eav + exe_total
```

So it becomes:

```r
    agency_total_eav := agency_total_eav - exe_total
```

Because increasing the HE with a multiplier is going to _reduce_ the overall base of each tax code, whereas in the vignette the base is mostly _increasing_ due to the removal of the freeze.

Keep in mind also that `agency_total_eav` already includes the value of all HEs, so your `m = 0` multiplier is actually the base, unchanged case.

**Comment by rross0** [comment]
Ah, ok great, that's what I was thinking. But I have like 30 mins to finish this and I couldn't take time to  think it through. Thanks.

**Comment by rross0** [comment]
@ccao-jardine @dfsnow @wrridgeway 

Policy idea: after appeals are processed, and levies are set, select the value of the homeowners exemption within each school district that produces a neutral tax structure (flat line, on average, in this graph). You could set some other bounding conditions like no giant increases in taxes for commercial, etc. Technically possible. Administratively impossible.... for now. 

![image](https://github.com/ccao-data/ptaxsim/assets/12952187/47396c4a-3f23-4d12-92ec-451819c14725)
