### ISSUE TITLE
Add Tax Year 2022 data

### ISSUE THREAD

**Issue by dfsnow** [ccao-data/ptaxsim#21]
We need to update the raw data sets used to generate the PTAXSIM database as tax year 2022 data becomes available from the Clerk, BoR, IDOR, and Treasurer. Once all TY2022 data is available, we will update both the R package and database. The following data sets need to be updated for 2022:

- [x] Tax code agency rates - [Clerk](https://www.cookcountyclerkil.gov/property-taxes/tax-extension-and-rates)
- [x] Agency tax rates - [Clerk](https://www.cookcountyclerkil.gov/property-taxes/tax-extension-and-rates)
- [x] CPI - IDOR
- [x] Equalization factors - IDOR
- [x] TIF data - [Clerk](https://www.cookcountyclerkil.gov/property-taxes/tifs-tax-increment-financing/tif-reports)
- [ ] PIN-level AV and exemptions - CCAO/Clerk (CLERKVALUES internal DB table)
- [ ] PIN-level total tax bills - CCAO/Treasurer (TAXBILLAMOUNTS internal DB table)
- [ ] Parcel geometries - Cook County GIS

Additionally, we should add 2022 unit/integration tests and update PTAXSIM vignettes:

- [ ] Update vignettes with 2022 data (where necessary)
- [ ] Update unit tests with 2022 data
- [ ] Update README with new package/DB version
- [ ] Bump DB and package version
- [ ] Pull at least 10 real second-installment 2022 tax bills to use for integration test

**Comment by erhla** [comment]
Forked to https://github.com/erhla/ptaxsim for now
